---
title: "code_chunk"
author: "Abhraneel Sarma"
date: "11/25/2019"
output: html_document
---


```{r setup, include=FALSE}
library(knitr)
#opts_knit$set(
#  echo = TRUE,
#  fig.width = 6, 
#  fig.height = 4,
#  output.dir="vignettes"
#)

library(dplyr)
library(tidyr)
library(purrr)
library(rlang)
```

```{r}
data("durante")

data.raw.study2 <- durante %>%
  mutate(
    Abortion = abs(7 - Abortion) + 1,
    StemCell = abs(7 - StemCell) + 1,
    Marijuana = abs(7 - Marijuana) + 1,
    RichTax = abs(7 - RichTax) + 1,
    StLiving = abs(7 - StLiving) + 1,
    Profit = abs(7 - Profit) + 1,
    FiscConsComp = FreeMarket + PrivSocialSec + RichTax + StLiving + Profit,
    SocConsComp = Marriage + RestrictAbortion + Abortion + StemCell + Marijuana
  )
```


```{r}
M = multiverse()

inside(M, {
  df <- data.raw.study2 %>%
    mutate( ComputedCycleLength = StartDateofLastPeriod - StartDateofPeriodBeforeLast )
  
  df <- df %>%
    mutate( NextMenstrualOnset = branch(menstrual_calculation, 
      "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength,
      "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength,
      "mc_option3" ~ StartDateNext)
    )
})

#multiverse_table(M)$.code[[1]]
multiverse_table(M)
```


```{multierse label=, name=}

```

```{r}
M2 = multiverse()

code(M2)
```


```{multiverse something, name = M2}
df <- data.raw.study2 %>% 
  mutate(Rel1 = branch(rel_def, 
                       "a" ~ 0, 
                       "b" ~ Rel2) 
         )

df <- df %>%
    mutate( ComputedCycleLength = StartDateofLastPeriod - StartDateofPeriodBeforeLast ) %>%
    mutate( NextMenstrualOnset = branch(menstrual_calculation, 
      "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength,
      "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength,
      "mc_option3" ~ StartDateNext)
    )
```

```{r}
map(multiverse_table(M2)$.code[[1]], ~ length(.x[[2]]))

map(multiverse_table(M2)$.code[[1]], ~ typeof(.x[[2]]))

print(df)
```

```{r}
M2$df
```

```{multiverse, name = M2}
df
```

```{r}
code(M2)
```



```{multiverse, name = M2}
df <- df %>%
    mutate(Relationship = branch( relationship_status, 
      "rs_option1" ~ factor(ifelse(Relationship==1 | Relationship==2, 'Single', 'Relationship')),
      "rs_option2" ~ factor(ifelse(Relationship==1, 'Single', 'Relationship')),
      "rs_option3" ~ factor(ifelse(Relationship==1, 'Single', ifelse(Relationship==3 | Relationship==4, 'Relationship', NA))) )
    ) %>%
    mutate(
      CycleDay = 28 - (NextMenstrualOnset - DateTesting),
      CycleDay = ifelse(CycleDay > 1 & CycleDay < 28, CycleDay, ifelse(CycleDay < 1, 1, 28))
    ) %>%
    filter( branch(cycle_length, 
      "cl_option1" ~ TRUE,
      "cl_option2" ~ ComputedCycleLength > 25 & ComputedCycleLength < 35,
      "cl_option3" ~ ReportedCycleLength > 25 & ReportedCycleLength < 35
    ))
```


```{r}
multiverse_table(M2)$.code[[1]]
```


```{r}
#lapply( code(M), get_parameter_code, list(menstrual_calculation = "mc_option1", relationship_status = "rs_option1") )

c_init <- list(expr({
    df <- data.raw.study2 %>% mutate(ComputedCycleLength = StartDateofLastPeriod - 
        StartDateofPeriodBeforeLast) %>% mutate(NextMenstrualOnset = branch(menstrual_calculation, 
        "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength, 
        "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength, 
        "mc_option3" ~ StartDateNext))
    }), expr({
      df <- df %>% mutate(Relationship = branch(relationship_status, 
          "rs_option1" ~ factor(ifelse(Relationship == 1 | Relationship == 
              2, "Single", "Relationship")), "rs_option2" ~ factor(ifelse(Relationship == 
              1, "Single", "Relationship")), "rs_option3" ~ factor(ifelse(Relationship == 
              1, "Single", ifelse(Relationship == 3 | Relationship == 
              4, "Relationship", NA)))))
  }) )


c_init <- expr({
    df <- data.raw.study2 %>% mutate(ComputedCycleLength = StartDateofLastPeriod - 
        StartDateofPeriodBeforeLast) %>% mutate(NextMenstrualOnset = branch(menstrual_calculation, 
        "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength, 
        "mc_option3" ~ StartDateNext))
    })
```


```{r}
compare_code <- function(x, y) {
  if (!is.list(x)) x <- list(x)
  if (!is.list(y)) y <- list(y)
  
  n <- max(length(x), length(y))
  length(x) <- n                      
  length(y) <- n
  
  mapply( function(.x, .y) identical(deparse(.x), deparse(.y)), x, y )
}

match( FALSE, compare_code(code(M), c_init) )
```


```{r}
code(M)[1:1]
```



```{r}
M = multiverse()

M$df = ~ data.raw.study2  %>%
    mutate( ComputedCycleLength = StartDateofLastPeriod - StartDateofPeriodBeforeLast ) %>%
    mutate(NextMenstrualOnset = branch(menstrual_calculation, 
      "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength,
      "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength,
      "mc_option3" ~ StartDateNext)
    )

M$df <- ~ df %>%
    mutate(Relationship = branch( relationship_status, 
      "rs_option1" ~ factor(ifelse(Relationship==1 | Relationship==2, 'Single', 'Relationship')),
      "rs_option2" ~ factor(ifelse(Relationship==1, 'Single', 'Relationship')),
      "rs_option3" ~ factor(ifelse(Relationship==1, 'Single', ifelse(Relationship==3 | Relationship==4, 'Relationship', NA))) )
    )

M$df <- ~ df %>%
    mutate(
      CycleDay = 28 - (NextMenstrualOnset - DateTesting),
      CycleDay = ifelse(CycleDay > 1 & CycleDay < 28, CycleDay, ifelse(CycleDay < 1, 1, 28))
    ) 
```


```{r}
M$df <- ~ df %>%
    mutate(
      CycleDay = 28 - (NextMenstrualOnset - DateTesting),
      CycleDay = ifelse(CycleDay > 1 & CycleDay < 28, CycleDay, ifelse(CycleDay < 1, 1, 28))
    ) 

M$df <- ~ df %>%
    filter( branch(cycle_length, 
      "cl_option1" ~ TRUE,
      "cl_option2" ~ ComputedCycleLength > 25 & ComputedCycleLength < 35,
      "cl_option3" ~ ReportedCycleLength > 25 & ReportedCycleLength < 35
    )) 

M$df <- ~ df %>%
    filter( branch(certainty,
        "cer_option1" ~ TRUE,
        "cer_option2" ~ Sure1 > 6 | Sure2 > 6
    )) 

M$df <- ~ df %>%
    mutate( Fertility = branch( fertile,
        "fer_option1" ~ factor( ifelse(CycleDay >= 7 & CycleDay <= 14, "high", ifelse(CycleDay >= 17 & CycleDay <= 25, "low", "medium")) ),
        "fer_option2" ~ factor( ifelse(CycleDay >= 6 & CycleDay <= 14, "high", ifelse(CycleDay >= 17 & CycleDay <= 27, "low", "medium")) ),
        "fer_option3" ~ factor( ifelse(CycleDay >= 9 & CycleDay <= 17, "high", ifelse(CycleDay >= 18 & CycleDay <= 25, "low", "medium")) ),
        "fer_option4" ~ factor( ifelse(CycleDay >= 8 & CycleDay <= 14, "high", "low") ),
        "fer_option5" ~ factor( ifelse(CycleDay >= 8 & CycleDay <= 17, "high", "low") )
    ))
```


```{r}
an_expr = list(expr(data.raw.study2  %>%
    mutate( ComputedCycleLength = StartDateofLastPeriod - StartDateofPeriodBeforeLast ) %>%
    mutate(NextMenstrualOnset = branch(menstrual_calculation, 
      "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength,
      "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength,
      "mc_option3" ~ StartDateNext)
    )))

append(an_expr, 
  expr(df %>%
    mutate(Relationship = branch( relationship_status, 
      "rs_option1" ~ factor(ifelse(Relationship==1 | Relationship==2, 'Single', 'Relationship')),
      "rs_option2" ~ factor(ifelse(Relationship==1, 'Single', 'Relationship')),
      "rs_option3" ~ factor(ifelse(Relationship==1, 'Single', ifelse(Relationship==3 | Relationship==4, 'Relationship', NA))) )
    ))
)
```




