---
title: "tree-structure"
author: "Abhraneel Sarma"
date: "7/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(rlang)
library(collections)
```

```{r}
data("durante")

df <- durante %>%
  mutate(
    Abortion = abs(7 - Abortion) + 1,
    StemCell = abs(7 - StemCell) + 1,
    Marijuana = abs(7 - Marijuana) + 1,
    RichTax = abs(7 - RichTax) + 1,
    StLiving = abs(7 - StLiving) + 1,
    Profit = abs(7 - Profit) + 1,
    FiscConsComp = FreeMarket + PrivSocialSec + RichTax + StLiving + Profit,
    SocConsComp = Marriage + RestrictAbortion + Abortion + StemCell + Marijuana
  )
```


```{r}
M <- multiverse()

inside(M, { 
  df <- df %>%
    mutate( ComputedCycleLength = StartDateofLastPeriod - StartDateofPeriodBeforeLast ) 
  
  df <- df %>%
    mutate( ComputedCycleLength = StartDateofLastPeriod - StartDateofPeriodBeforeLast )
  
  df <- df %>%
    mutate( NextMenstrualOnset = branch(menstrual_calculation, 
      "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength,
      "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength,
      "mc_option3" ~ StartDateNext)
    )
})

inside(M, {
  df <- df %>%
      mutate(Relationship = branch( relationship_status, 
        "rs_option1" ~ factor(ifelse(Relationship==1 | Relationship==2, 'Single', 'Relationship')),
        "rs_option2" ~ factor(ifelse(Relationship==1, 'Single', 'Relationship'))
      ))
  
  df <- df %>%
      filter( branch(certainty,
        "cer_option1" ~ Sure1 > 6 | Sure2 > 6,
        "cer_option2" ~ TRUE
      ))
})
```


```{r}
M = multiverse()
inside(M, {x <- branch(value_x, "a", 0, 5, 10, 14)} )

M$x

execute_multiverse(M)
```


```{r}
from_universe_i(M, 5, x)
```


```{r}
M <- multiverse()

dat1 <- data.frame(x = 1:10) %>% mutate( y = x^2 + sample(10:20, 10))
  
inside(M, { 
  dat1 <- dat1 %>% mutate( q = branch( value_v, 1, 2)) 
}, .label = "1")

inside(M, { 
  dat1 <- dat1 %>% mutate( z = branch( value_y, log(y), y)) 
}, .label = "2")

inside(M, { 
  dat1 <- dat1 %>% mutate( q = branch( value_v, 1, 2)) 
}, .label = "1")
```


```{r}
M <- multiverse()

x <- myfun()
```


```{r}
M <- multiverse()
inside(M, {branch( x_values, 0, 3, 5 )})

parameters(M)
```


```{r}
execute_multiverse2 <- function(multiverse, .universe = 1) {
  m_diction = attr(multiverse, "multiverse")$multiverse_diction
  .level = attr(multiverse, "multiverse")$unchanged_until
  
  .to_exec = tail(seq_len(m_diction$size()), n = m_diction$size() - .level)
  invisible(lapply(.to_exec, exec_all, .m_diction = m_diction) )
}

exec_all <- function(.m_diction, .i) {
  .code_list <- lapply(.m_diction$get(as.character(.i)), `[[`, "code")
  .env_list <- lapply(.m_diction$get(as.character(.i)), `[[`, "env")
  
  .results <- mapply(execute_code_from_universe, .code_list, .env_list)
}


execute_multiverse2(M)
```



```{r}
test_multiverse1 <- function() {
  M <- multiverse()

  inside(M, {
    df <- df %>%
      mutate( ComputedCycleLength = StartDateofLastPeriod - StartDateofPeriodBeforeLast ) %>%
      mutate( NextMenstrualOnset = branch(menstrual_calculation, 
        "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength,
        "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength,
        "mc_option3" ~ StartDateNext)
      ) %>%
      mutate(Relationship = branch( relationship_status, 
        "rs_option1" ~ factor(ifelse(Relationship==1 | Relationship==2, 'Single', 'Relationship')),
        "rs_option2" ~ factor(ifelse(Relationship==1, 'Single', 'Relationship')),
        "rs_option3" ~ factor(ifelse(Relationship==1, 'Single', ifelse(Relationship==3 | Relationship==4, 'Relationship', NA))) )
      ) %>%
      mutate(
        CycleDay = 28 - (NextMenstrualOnset - DateTesting),
        CycleDay = ifelse(CycleDay > 1 & CycleDay < 28, CycleDay, ifelse(CycleDay < 1, 1, 28))
      ) %>%
      filter( branch(cycle_length, 
        "cl_option1" ~ TRUE,
        "cl_option2" ~ ComputedCycleLength > 25 & ComputedCycleLength < 35,
        "cl_option3" ~ ReportedCycleLength > 25 & ReportedCycleLength < 35
      )) %>%
      filter( branch(certainty,
        "cer_option1" ~ TRUE,
        "cer_option2" ~ Sure1 > 6 | Sure2 > 6
      )) %>%
      mutate( Fertility = branch( fertile,
        "fer_option1" ~ factor( ifelse(CycleDay >= 7 & CycleDay <= 14, "high", ifelse(CycleDay >= 17 & CycleDay <= 25, "low", "medium")) ),
        "fer_option2" ~ factor( ifelse(CycleDay >= 6 & CycleDay <= 14, "high", ifelse(CycleDay >= 17 & CycleDay <= 27, "low", "medium")) ),
        "fer_option3" ~ factor( ifelse(CycleDay >= 9 & CycleDay <= 17, "high", ifelse(CycleDay >= 18 & CycleDay <= 25, "low", "medium")) ),
        "fer_option4" ~ factor( ifelse(CycleDay >= 8 & CycleDay <= 14, "high", "low") ),
        "fer_option5" ~ factor( ifelse(CycleDay >= 8 & CycleDay <= 17, "high", "low") )
      ))
  })
}

test_multiverse2 <- function() {
  M2 <- multiverse()
  
  inside2(M2, {
    df <- df %>%
      mutate( ComputedCycleLength = StartDateofLastPeriod - StartDateofPeriodBeforeLast )
    
    df <- df %>%
      mutate( NextMenstrualOnset = branch(menstrual_calculation, 
        "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength,
        "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength,
        "mc_option3" ~ StartDateNext)
      )
  })
  
  inside2(M2, {
    df <- df %>%
      mutate(Relationship = branch( relationship_status, 
        "rs_option1" ~ factor(ifelse(Relationship==1 | Relationship==2, 'Single', 'Relationship')),
        "rs_option2" ~ factor(ifelse(Relationship==1, 'Single', 'Relationship')),
        "rs_option3" ~ factor(ifelse(Relationship==1, 'Single', ifelse(Relationship==3 | Relationship==4, 'Relationship', NA))) )
      )
  })
  
  inside2(M2, {
    df <- df %>%
      filter( branch(cycle_length, 
        "cl_option1" ~ TRUE,
        "cl_option2" ~ ComputedCycleLength > 25 & ComputedCycleLength < 35,
        "cl_option3" ~ ReportedCycleLength > 25 & ReportedCycleLength < 35
      ))
  })
  
  inside2(M2, {
    df <- df %>%
      filter( branch(certainty,
        "cer_option1" ~ TRUE,
        "cer_option2" ~ Sure1 > 6 | Sure2 > 6
      )) %>%
      mutate( Fertility = branch( fertile,
        "fer_option1" ~ factor( ifelse(CycleDay >= 7 & CycleDay <= 14, "high", ifelse(CycleDay >= 17 & CycleDay <= 25, "low", "medium")) ),
        "fer_option2" ~ factor( ifelse(CycleDay >= 6 & CycleDay <= 14, "high", ifelse(CycleDay >= 17 & CycleDay <= 27, "low", "medium")) ),
        "fer_option3" ~ factor( ifelse(CycleDay >= 9 & CycleDay <= 17, "high", ifelse(CycleDay >= 18 & CycleDay <= 25, "low", "medium")) ),
        "fer_option4" ~ factor( ifelse(CycleDay >= 8 & CycleDay <= 14, "high", "low") ),
        "fer_option5" ~ factor( ifelse(CycleDay >= 8 & CycleDay <= 17, "high", "low") )
      ))
  })
}

microbenchmark::microbenchmark(test_multiverse1(), test_multiverse2())
```


```{r}
M2 <- multiverse()
attr(M2, "multiverse")$multiverse_diction$clear()

inside2(M2, {
  df <- df %>%
    mutate( ComputedCycleLength = StartDateofLastPeriod - StartDateofPeriodBeforeLast )
  
  df <- df %>%
    mutate( NextMenstrualOnset = branch(menstrual_calculation, 
      "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength,
      "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength
    ))
}, .label = "1")

inside2(M2, {
  df <- df %>%
      mutate(Relationship = branch( relationship_status, 
        "rs_option1" ~ factor(ifelse(Relationship==1 | Relationship==2, 'Single', 'Relationship')),
        "rs_option2" ~ factor(ifelse(Relationship==1, 'Single', 'Relationship'))
      ))
}, .label = "2")

inside2(M2, {
  df <- df %>%
      filter( branch(certainty,
        "cer_option1" ~ TRUE,
        "cer_option2" ~ Sure1 > 6 | Sure2 > 6
      ))
}, .label = "3")
```


```{r}
attr(M2, "multiverse")$multiverse_diction$as_list()
attr(M2, "multiverse")$multiverse_diction$get("1")$as_list()
code(M2)
```

## Tree structure optimisation

```{r}
d <- ordered_dict()
parameter_set <- c()

an_expr.0 <- quote({
  df <- df %>%
    mutate( ComputedCycleLength = StartDateofLastPeriod - StartDateofPeriodBeforeLast )
})

d$set(1, queue())
d$get(1)$push(list(env = new.env(parent = globalenv()), parameter_assignment = NULL, code = an_expr.0))

d$get(1)$as_list() %>% length()
```

```{r}
m_obj <- list(code = an_expr.1)
```


```{r}
an_expr.1 <- list(quote({
  df <- df %>%
    mutate( NextMenstrualOnset = branch(menstrual_calculation, 
      "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength,
      "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength,
      "mc_option3" ~ StartDateNext)
    )
  
  df <- df %>%
      mutate(Relationship = branch( relationship_status, 
        "rs_option1" ~ factor(ifelse(Relationship==1 | Relationship==2, 'Single', 'Relationship')),
        "rs_option2" ~ factor(ifelse(Relationship==1, 'Single', 'Relationship'))
      ))
}))
```


```{r}
# returns a queue of length = <number of parameter combinations in a code block>
create_parameter_option_list <- function(.expr, .param_options) {
  df <- data.frame( lapply(expand.grid(.param_options, KEEP.OUT.ATTRS = FALSE), unlist), stringsAsFactors = FALSE )
  
  # gets the environments from the previous code block in the multiverse
  # these will be the parents for the new environments created from the execution
  # of a new code block.
  parent.envs <- lapply(d$get(tail(unlist(d$keys()), n = 1))$as_list(), `[[`, "env")
  
  lapply(seq_len(nrow(df)), function(i) {
      .p <- lapply(df, "[[", i)
      
      # new envs per parent env: nrow(df)/length(parent.envs)
      # number of parent env: length(parent.envs)
      # parent: parent.envs[[ceiling(i/(nrow(df)/length(parent.envs)))]]
      list(
        env = new.env(parent = parent.envs[[ceiling(i/(nrow(df)/length(parent.envs)))]]), 
        parameter_assignment = .p, 
        code = get_code(.expr, .p)
      ) 
  }) %>%
    queue(items = .)
}

#d$set(tail(unlist(d$keys()), n = 1) + 1, x)

parse_multiverse_expr <- function(.expr, .name = NULL) {
  .expr = expand_branch_options(.expr)
  .loc = length(m_obj$code)
  
  if (is_null(m_obj$code)) {
    if (is.null(.name)) .c = list(.expr) 
    else {
      .c = list()
      .c[[.name]] = .expr
    }
  } else {
    if (is.null(.name))  .c = append(m_obj$code[1:.loc], .expr)
    else {
      .c = m_obj$code
      .c[[.name]] = .expr
    }
  }
  
  parameter_options <- unlist(lapply(.c, function(x) get_parameter_conditions(x)$parameters), recursive = FALSE)
  parameter_set <- c(parameter_set, setdiff(names(parameter_options), parameter_set))
  
  create_parameter_option_list(.expr, parameter_options)
}
```


```{r}
x <- parse_multiverse_expr`(an_expr.2)

y <- map(x$as_list(), ~ parent.env(.$env))
```


```{r}
an_expr.2 <- list(quote({
  df <- df %>%
      filter( branch(certainty,
        "cer_option1" ~ TRUE,
        "cer_option2" ~ Sure1 > 6 | Sure2 > 6
      ))
}))

# n <- nrow(df)

get_code(an_expr.2, list(menstrual_calculation = "mc_option1", relationship_status = "rs_option1", certainty = "cer_option2"))
```






```{r}
tree.df <- expand(M) %>% select(-.results)

l <- lapply(parameter_options, length)
n <- cumprod(unname(l))
.env_list <- list()
parents <- lapply(1:length(n), function(i) {
  lapply(1:n[[i]], function(y) {
    if (i <= 1) {
      .env_list <<- append(.env_list, new.env(parent = globalenv()))
      return(0)
    }
    else { 
      if (i > 2) {
        .env_list <<- append(.env_list, new.env( parent = .env_list[[ (ceiling(y / l[[i]]) + sum(n[1:(i-2)])) ]]) )
        return(ceiling(y / l[[i]]) + sum(n[1:(i-2)]))
      }
      else {
        .env_list <<- append(.env_list, new.env( parent = .env_list[[ (ceiling(y / l[[i]])) ]]) ) 
        return(ceiling(y / l[[i]]))
      }
    }
  })
})

unlist(parents)

code(M)

expand(M)$.code[[1]]
```
