---
title: "Integrating tangle.js with the output on multiverse notebook analysis"
output: html_document
---

```{r setup, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(broom)
devtools::load_all(".")
```

```{r, chunk-setup, include=FALSE, eval=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  eval = if (isTRUE(exists("params"))) params$EVAL else FALSE,
  fig.width = 6, 
  fig.height = 4
)
```

## Multiverse case study #4

```{r}
data("hurricane")

hurricane_data <- hurricane %>%
    # rename some variables
    rename(
        year = Year,
        name = Name,
        dam = NDAM,
        death = alldeaths,
        female = Gender_MF,
        masfem = MasFem,
        category = Category,
        pressure = Minpressure_Updated_2014,
        wind = HighestWindSpeed
    ) %>%
    # create new variables
    # which are relevant later on
    mutate(
        post = ifelse(year>1979, 1, 0),
        zcat = as.numeric(scale(category)),
        zpressure = -scale(pressure),
        zwind = as.numeric(scale(wind)),
        z3 = as.numeric((zpressure + zcat + zwind) / 3)
    )
```


## Multiverse Analysis

To implement a multiverse analysis, we first need to create the `js parameter('masfem')` object:

```{r}
M = multiverse()
```

```{multiverse label = variable_definitions, inside = M}
df = hurricane_data

df = df %>%
    mutate(
        femininity = branch(femininity_calculation,
          "masfem" ~ masfem,
          "female" ~ female
        ),
        damage = branch(damage_transform,
          "no_transform" ~ identity(dam),
          "log_transform" ~ log(dam)
        )
    )
```


```{multiverse default-m-5, inside = M}
mean(df$femininity)
hist(df$femininity)
```


```{r}
expand(M)
```


```{r}
size(M) # 4
expand(M)$.results[[1]]
```



```{r, include = FALSE}
out = evaluate::evaluate(
  input = "hist(df$femininity)",
  new_device = FALSE, 
  envir = expand(M)$.results[[1]]
)
```


```{r, include = FALSE}
out = evaluate::evaluate(
  input = "hist(df$femininity)",
  new_device = FALSE, 
  envir = expand(M)$.results[[3]]
)
```
