---
title: "Untitled"
author: "Abhraneel Sarma"
date: "2/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(dplyr)
library(tidyr)
library(purrr)
library(rlang)
library(multiverse)
library(readr)
library(lme4)
```

```{r prepare_data, message=FALSE}
speed_data <- read_csv('../data/speed_data.csv')

#remove retake participants
speed_data <- subset(speed_data, retake != 1)

#demographics information
demographics_data <- subset(speed_data, select = c(uuid, age, device, dyslexia, education, gender, language, retake), !duplicated(uuid))

head(speed_data)
```


```{r}
M = multiverse()
```

```{multiverse, label = default-m-1, inside = M}
speed_data <- speed_data %>%
  mutate(speed = branch(speed_calculation, 
    "speed_calculation_option1" ~ num_words/(adjust_rt/60000),
    "speed_calculation_option2" ~ num_words/(rt/60000))
  )

iqr = IQR(speed_data[speed_data$dyslexia_bin == 0,]$speed, na.rm=TRUE)
cutoff_high = median(speed_data$speed) +3*iqr

twobelow = mean(speed_data$speed) - 2*sd(speed_data$speed)
twoabove = mean(speed_data$speed) + 2*sd(speed_data$speed)

speed_data <- speed_data %>%    
  filter(branch(speed_outlier_filtering, 
    "speed_outlier_filtering_option1" ~ speed > 10 | speed < cutoff_high,
    "speed_outlier_filtering_option2" ~ speed > twobelow | speed < twoabove
  )) %>%
  filter(branch(comprehension_score,
      "comprehension_score_option1" ~ correct_rate >= 2/3,
      "comprehension_score_option2" ~ correct_rate >= 1/3
  )) %>%
  mutate(speed = branch(transform_speed,
      "transform_speed_option1" ~ speed,
      "transform_speed_option2" ~ log(speed)
  ))

# comments: For people who know additional language (besides English), how does that affect Reading speed
# or maybe the type of language that they know
# instead of using a binary variable (english native), use langauge 
model <- branch(data_model,
  "model_1" ~ lmer(speed ~ as.factor(page_condition)*as.factor(dyslexia) + img_width + num_words + age + english_native + (1 | uuid), data = speed_data),
  "model_2" ~ lmer(speed ~ as.factor(page_condition)*as.factor(dyslexia) + img_width + num_words + age + english_native + Flesch_Kincaid + (1 | uuid), data = speed_data),
  "model_3" ~ lmer(speed ~ as.factor(page_condition)*as.factor(dyslexia) + img_width + num_words + age + english_native + Flesch_Kincaid + (1 | uuid), data = speed_data),
  "model_4" ~ lmer(speed ~ as.factor(page_condition)*as.factor(dyslexia) + img_width + num_words + age + language + Flesch_Kincaid + (1 | uuid), data = speed_data),
   "model_5" ~ lmer(speed ~ as.factor(page_condition)*as.factor(dyslexia) + img_width + num_words + age + education + geneder + language + Flesch_Kincaid + (1 | uuid), data = speed_data),
   "model_6" ~ lmer(speed ~ as.factor(page_condition)*as.factor(dyslexia) + img_width*num_words + age + education + geneder + language + Flesch_Kincaid + (1 | uuid), data = speed_data))
```

