---
title: "code_chunk"
author: "Abhraneel Sarma"
date: "11/25/2019"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{The most basic multiverse example: calculating the mean}
  %\usepackage[UTF-8]{inputenc}
---


```{r setup, include=FALSE}
library(knitr)
#opts_knit$set(
#  echo = TRUE,
#  fig.width = 6, 
#  fig.height = 4,
#  output.dir="vignettes"
#)

library(dplyr)
library(tidyr)
library(purrr)
library(rlang)
#library(multiverse)
```


```{r}
M = multiverse()
```

```{r prepare_data, message=FALSE}
speed_data <- readr::read_csv('data/speed_data.csv')
#calculate reading speed in WPM
speed_data$speed <- speed_data$num_words/(speed_data$adjust_rt/60000)

#remove retake participants
speed_data <- subset(speed_data, retake != 1)

head(speed_data)
```

```{multiverse label = default-m-1, inside = M}
# remove outliers
iqr = IQR(speed_data[speed_data$dyslexia_bin == 0,]$speed,na.rm=TRUE)
# cutoff_high = median(speed_data$speed) +3*iqr #3*iqr=645, cutoff_high = 928
median = median(speed_data$speed)

#-------remove trials based on speed-------
# (1) values greater than median + 3 * IQR_Range, or
# (2) values less than 10 
# result_analysis <- speed_data[! speed_data$speed > cutoff_high, ]
# result_analysis <- result_analysis[ ! result_analysis$speed < 10,]

#-------remove smartphone users-------
# result_analysis <- result_analysis[! result_analysis$device == 'smartphone',]
#removed 64 smartphone users, 363 trials

# filtering 
result_analysis <- speed_data %>%
  filter(branch(outlier,
    "default" ~ speed < median + 3 * iqr & speed > 10,
    "strict" ~ speed < median + 2 * iqr & speed > 10
  )) %>%
  filter(branch(device,
    "default" ~ device != "smartphone",
    "strict" ~ !device %in% c("smartphone", "other") & !is.na(device)
  ))

#-------remove trials based on comprehension < 2/3-------
result_analysis <- result_analysis[ ! result_analysis$correct_rate < .6,]
#remove 111 trials
```

```{multiverse label = default-m-2, inside = M}
#dyslexia in three groups
model <- branch(model_spec,
  "default" ~ lmer(log(speed) ~ as.factor(page_condition)*as.factor(dyslexia) + img_width + num_words + age + english_native + (1 | uuid), data = result_analysis),
  "conservative" ~ lmer(log(speed) ~ as.factor(page_condition)*as.factor(dyslexia) + img_width + english_native + (1 | uuid), data = result_analysis),
  "width_dyslexia_interaction" ~ lmer(log(speed) ~ as.factor(page_condition)*as.factor(dyslexia) + img_width*as.factor(dyslexia) + num_words + age + english_native + (1 | uuid), data = result_analysis),
  "width_dyslexia_interaction_conservative" ~ lmer(log(speed) ~ as.factor(page_condition)*as.factor(dyslexia) + img_width*as.factor(dyslexia) + english_native + (1 | uuid), data = result_analysis))
AIC(model)
summary(model)
```


```{r}
multiverse_table(M)
```

```{r}
M$model
```

```{r}
execute_multiverse(M)
```



