# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', suffix: 'quick', not_cran: 'false', check_options: '"--as-cran", "--no-build-vignettes", "--ignore-vignettes", "--no-examples"'}
          - {os: macOS-latest, r: 'release', suffix: 'quick', not_cran: 'false', check_options: '"--no-build-vignettes", "--no-examples"'}
          # full checks on linux
          - {os: ubuntu-latest, r: 'devel', suffix: '', not_cran: 'true', check_options: '"--as-cran"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest", http-user-agent: 'release'}
          - {os: ubuntu-latest, r: 'release', suffix: '', not_cran: 'true', check_options: '"--as-cran"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
          # quick checks on linux
          - {os: ubuntu-latest, r: 'release', suffix: 'quick', not_cran: 'false', check_options: '"--as-cran", "--no-build-vignettes", "--ignore-vignettes"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
          - {os: ubuntu-latest, r: 'oldrel-1', suffix: 'quick', not_cran: 'false', check_options: '"--as-cran", "--no-build-vignettes", "--ignore-vignettes"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
          - {os: ubuntu-latest, r: 'oldrel-2', suffix: 'quick', not_cran: 'false', check_options: '"--as-cran", "--no-build-vignettes", "--ignore-vignettes"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
          - {os: ubuntu-latest, r: 'oldrel-3', suffix: 'quick', not_cran: 'false', check_options: '"--as-cran", "--no-build-vignettes", "--ignore-vignettes"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
          - {os: ubuntu-latest, r: 'oldrel-4', suffix: 'quick', not_cran: 'false', check_options: '"--as-cran", "--no-build-vignettes", "--ignore-vignettes"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}


    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_FORCE_SUGGESTS_: false

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-1-

      - name: Install system dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "18.04"))')

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}
      
      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          _R_CHECK_FORCE_SUGGESTS_: false
          NOT_CRAN: ${{ matrix.config.not_cran }}
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--ignore-vignettes", "--as-cran", ${{ matrix.config.check_options }}), build_args = "--no-build-vignettes", error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Test coverage
        if: matrix.config.r == 'release' && runner.os == 'Windows'
        run: covr::codecov()
        shell: Rscript {0}
